const projects = {
  buildsmart: { number: '01', type: 'Web application', title: 'Build<br /><em>Smart.</em>', summary: 'A construction project management platform designed to keep teams, deadlines, and site progress in one clear workflow.', image: 'assets/projects/buildsmart.png', accent: '#c7ea4e', challenge: 'Built to turn fragmented construction updates into a focused workspace for project teams.', description: 'BuildSmart brings project tracking, reports, team coordination, and progress visibility together in one practical web application. The experience is designed around the daily decisions that keep construction projects moving.', tech: ['React', 'Node.js', 'PostgreSQL', 'Tailwind CSS'], stats: [['Focus', 'Project delivery'], ['Platform', 'Web application'], ['Role', 'Full-stack development']], next: 'kottu-special' },
  'kottu-special': { number: '02', type: 'Web application', title: 'Kottu<br /><em>Special.</em>', summary: 'A restaurant ordering and reservation experience that makes Sri Lankan food discovery feel immediate and memorable.', image: 'assets/projects/resta.png', accent: '#f2b633', challenge: 'Designed a clear path from menu discovery to order placement and table reservations.', description: 'Kottu Special combines a warm food-first interface with practical ordering flows. The product helps diners browse dishes, reserve a table, and place an order without losing the personality of the restaurant.', tech: ['Next.js', 'MongoDB', 'Stripe', 'Tailwind CSS'], stats: [['Focus', 'Restaurant flow'], ['Platform', 'Web application'], ['Role', 'Product development']], next: 'ceylon-imports' },
  'ceylon-imports': { number: '03', type: 'E-commerce website', title: 'Ceylon<br /><em>Imports.</em>', summary: 'A premium storefront that brings authentic Sri Lankan products to an international audience.', image: 'assets/projects/ceymos-lanka.png', accent: '#8fc36a', challenge: 'Created a product story and shopping experience that communicates origin, quality, and trust.', description: 'Ceylon Imports is an e-commerce concept built around Sri Lankan spices, tea, and natural products. It uses rich visual storytelling and clean navigation to make a global storefront feel connected to its source.', tech: ['Shopify', 'Liquid', 'JavaScript', 'Figma'], stats: [['Focus', 'Global commerce'], ['Platform', 'Storefront'], ['Role', 'UI / UX development']], next: 'plant-disease' },
  'plant-disease': { number: '04', type: 'AI project', title: 'Plant disease<br /><em>detector.</em>', summary: 'An AI-assisted system that helps identify plant diseases from leaf images and guides the next action.', image: 'assets/projects/plant-disease-dashboard.png', accent: '#65d892', challenge: 'Made machine-learning results easier to understand through a simple, confidence-led interface.', description: 'The Plant Disease Detector combines image analysis with a clear dashboard that surfaces diagnosis confidence and practical recommendations. The focus is not only detection, but making the output useful to a real person.', tech: ['Python', 'TensorFlow', 'OpenCV', 'Machine Learning'], stats: [['Focus', 'Image analysis'], ['Platform', 'AI system'], ['Role', 'ML / interface design']], next: 'auto-rover' },
  'auto-rover': { number: '05', type: 'IoT / Healthcare', title: 'Auto<br /><em>Rover.</em>', summary: 'An IoT rover concept created to explore safer, more responsive healthcare assistance.', image: 'assets/projects/auto-rover.jpg', accent: '#91c9ef', challenge: 'Connected physical hardware, sensors, and control logic into one dependable prototype.', description: 'Auto Rover is a hands-on IoT project that investigates how a small autonomous rover can support healthcare environments. It brings together embedded programming, sensors, and practical movement control.', tech: ['Arduino', 'IoT', 'Sensors', 'Embedded C'], stats: [['Focus', 'Healthcare assistance'], ['Platform', 'IoT prototype'], ['Role', 'Embedded development']], next: 'hospital-management' },
  'hospital-management': { number: '06', type: 'Mobile application', title: 'Hospital<br /><em>Management.</em>', summary: 'A mobile workflow application that makes hospital operations and patient updates easier to manage.', image: 'assets/projects/hospital-management-mobile.png', accent: '#8eb8ff', challenge: 'Translated complex hospital workflows into calm, usable mobile screens for busy staff.', description: 'Hospital Management is a mobile-first concept for tracking appointments, patient information, and core hospital workflows. It prioritizes quick scanning, clear status updates, and an interface that stays useful under pressure.', tech: ['Flutter', 'Firebase', 'Dart', 'Mobile UI'], stats: [['Focus', 'Care workflows'], ['Platform', 'Mobile application'], ['Role', 'Mobile development']], next: 'buildsmart' },
};
const projectKey = document.body.dataset.project;
const project = projects[projectKey];
if (project) {
  document.documentElement.style.setProperty('--accent', project.accent);
  document.title = `${project.title.replace(/<[^>]+>/g, '').replace('<br />', ' ')} | Chamidu Prabodya`;
  document.querySelector('[data-type]').textContent = `${project.number} / ${project.type}`;
  document.querySelector('[data-title]').innerHTML = project.title;
  document.querySelector('[data-summary]').textContent = project.summary;
  document.querySelector('[data-image]').src = project.image;
  document.querySelector('[data-image]').alt = `${project.title.replace(/<[^>]+>/g, '').replace('<br />', ' ')} preview`;
  document.querySelector('[data-index]').textContent = `${project.number} / 06`;
  document.querySelector('[data-challenge]').textContent = project.challenge;
  document.querySelector('[data-description]').textContent = project.description;
  document.querySelector('[data-tech]').innerHTML = project.tech.map((item) => `<li>${item}</li>`).join('');
  document.querySelector('[data-stats]').innerHTML = project.stats.map(([label, value]) => `<article class="project-stat"><span>${label}</span><strong>${value}</strong></article>`).join('');
  const next = projects[project.next];
  const nextLink = document.querySelector('[data-next]');
  nextLink.href = `project-${project.next}.html`;
  nextLink.innerHTML = `<span>Next project</span><em>${next.title.replace('<br />', ' ').replace(/<[^>]+>/g, '')}</em><span>↗</span>`;
}
if (window.gsap && window.ScrollTrigger) {
  gsap.registerPlugin(ScrollTrigger);
  gsap.timeline().from('.project-nav', { autoAlpha: 0, duration: .45, y: -16 }).from('.project-label', { autoAlpha: 0, duration: .35, y: 12 }, '-=.15').from('.project-title > *', { duration: .85, ease: 'power4.out', stagger: .12, yPercent: 115 }, '-=.08').from('.project-summary, .project-links', { autoAlpha: 0, duration: .5, stagger: .1, y: 20 }, '-=.35').from('.project-visual img', { duration: 1.1, ease: 'power3.out', scale: 1.12 }, '-=.85');
  gsap.utils.toArray('.project-overview, .project-stats, .project-build-inner, .project-next').forEach((element) => gsap.from(element, { autoAlpha: 0, duration: .8, ease: 'power3.out', y: 45, scrollTrigger: { trigger: element, start: 'top 82%', once: true } }));
  gsap.to('.project-visual img', { ease: 'none', yPercent: 12, scrollTrigger: { trigger: '.project-hero', start: 'top top', end: 'bottom top', scrub: true } });
}
